exclude: [Gemfile, bower.json, Rakefile]

name: Angelika.me
description: A blog about Ruby, Rails, JavaScript and web development in general.
url: http://angelika.me

permalink: pretty

tag_page_layout: tag_page
tag_page_dir: tag

about:
  repo: https://github.com/angelikatyborska/blog
  linkedin: https://linkedin.com/in/angelika-tyborska-330a6bb0
  github: https://github.com/angelikatyborska
  exercism: http://exercism.io/angelikatyborska

assets:
  assets:
    - "*.otf"
    - "*.eot"
    - "*.svg"
    - "*.ttf"
    - "*.woff"
    - "*.woff2"
  sources:
    - _assets/bower

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"