exclude: [Gemfile, bower.json, Rakefile]

tag_page_layout: tag_page
tag_page_dir: tag

about:
  repo: https://github.com/angelikatyborska/blog
  linkedin: https://linkedin.com/in/angelika-tyborska-330a6bb0
  github: https://github.com/angelikatyborska

assets:
  assets:
    - "*.otf"
    - "*.eot"
    - "*.svg"
    - "*.ttf"
    - "*.woff"
    - "*.woff2"
  sources:
    - _assets/css
    - _assets/images
    - _assets/bower

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"