exclude: [scss, Gemfile]

tag_page_layout: tag_page
tag_page_dir: tag

sass:
  sass_dir: _assets/css

assets:
  assets:
    - "*.png"
    - "screen.scss"
  compress:
    css: true

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"