exclude: [Gemfile, bower.json, Rakefile, README, vendor, node_modules]

name: Angelika.me
description: Angelika Tyborska's personal blog about web development.
url: https://angelika.me
twitter_handler: "@atyborska93"
permalink: pretty

tag_page_layout: tag_page
tag_page_dir: tag

about:
  repo: https://github.com/angelikatyborska/angelika.me
  linkedin: https://linkedin.com/in/angelika-tyborska-330a6bb0
  mastodon: https://mas.to/@angelikatyborska
  github: https://github.com/angelikatyborska
  exercism: https://exercism.io/profiles/angelikatyborska
  lastfm: https://www.last.fm/user/atyborska93
  flickr: https://www.flickr.com/photos/192384616@N03

assets:
  assets:
    - "*.otf"
    - "*.eot"
    - "*.svg"
    - "*.ttf"
    - "*.woff"
    - "*.woff2"
  sources:
    - _assets/bower
    - _assets/fonts
  defaults:
    img:
      integrity: false

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      toc: true
  -
    scope:
      path: "_og_images/**/*"
    values:
      sitemap: false
  -
    scope:
      path: "default_og_image/**/*"
    values:
      sitemap: false

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

pagination:
  enabled: true
  per_page: 20
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

collections:
  og_images:
    output: true
    permalink: /og_images/:slug/
