exclude: [Gemfile, bower.json, Rakefile, README, vendor]

name: Angelika.me
description: Angelika Tyborska's personal blog about web development.
url: http://angelika.me
twitter_handler: "@atyborska93"
permalink: pretty

tag_page_layout: tag_page
tag_page_dir: tag

about:
  repo: https://github.com/angelikatyborska/angelika.me
  linkedin: https://linkedin.com/in/angelika-tyborska-330a6bb0
  twitter: https://twitter.com/atyborska93
  github: https://github.com/angelikatyborska
  exercism: https://exercism.io/profiles/angelikatyborska
  dev: https://dev.to/atyborska93

assets:
  assets:
    - "*.otf"
    - "*.eot"
    - "*.svg"
    - "*.ttf"
    - "*.woff"
    - "*.woff2"
  sources:
    - _assets/bower
    - assets/bower

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

pagination:
  enabled: true
  per_page: 5
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
